project_id = "ybimcjurdmjmdjzfbfup"

[functions.consulta-base-sp]
verify_jwt = false

[functions.consulta-bin]
verify_jwt = false

[functions.asaas-create-payment]
verify_jwt = false

[functions.asaas-check-payment]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.enviar-email-pedido]
verify_jwt = false

[functions.split-facil-webhook]
verify_jwt = false